### PR TITLE
Support To Run Specific Test Case or List of Test cases from the Test classes

### PR DESCRIPTION
**Pull request by SushanthN22**
@saikrishna321 Please let me know your comments

### CODE REVIEW

**Comment by AnilPatidar** [comment]
It's really a must have feature. it helps to run specific test by mentioning specific test method name . it is working for us.

**Comment by SushanthN** [comment]
@saikrishna321 @SrinivasanTarget Let me know if you need more clarity on this. Please review and provide your comments

**Comment by saikrishna321** [comment]
@SushanthN22 Thanks for the PR.  Can you show an example on how the user side test would be?

**Comment by saikrishna321** [comment]
@SushanthN22 any updates on this ?

**Comment by saikrishna321** [comment]
@AnilPatidar How are you using this feature? I would like to close this PR.

**Comment by saikrishna321** [comment]
@SushanthN So from user side how will this be configured?

**Comment by SushanthN22** [comment]
> @SushanthN So from user side how will this be configured?

@saikrishna321 User need to pass like below,

**Comment by SushanthN22** [comment]
> > @SushanthN So from user side how will this be configured?
> 
> @saikrishna321 The user need to pass the list of test methods in a array list, so that parallel.xml will be created only for the test methods
> 
> ```
>    `List<String> tests = new ArrayList<>();
>     ATDRunner atdRunner = new ATDRunner();
>     tests.add("test1");
>     tests.add("test2");
>     boolean hasFailures = atdRunner.runner("com.appium.webtest", tests);`
> ```

`<suite thread-count="1" parallel="methods" data-provider-thread-count="1" name="RummyCircle" verbose="2">
<listeners>
<listener class-name="com.appium.manager.AppiumParallelMethodTestListener"/>
<listener class-name="com.games24x7.e2e.core.listener.TestNGTestListener"/>
<listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"/>
<listener class-name="com.games24x7.e2e.core.listener.Retrylistener"/>
</listeners>
<test thread-count="1" parallel="methods" name="regression" verbose="2">
<classes>
<class name="com.games24x7.e2e.tests.gametable.LoginTest">
<methods>
<include name="test1"/>
</methods>
</class>
</classes>
</test>

</suite>`

**Comment by SushanthN22** [comment]
`<suite thread-count="1" parallel="methods" data-provider-thread-count="1" name="RummyCircle" verbose="2">
<listeners>
<listener class-name="com.appium.manager.AppiumParallelMethodTestListener"/>
<listener class-name="com.games24x7.e2e.core.listener.TestNGTestListener"/>
<listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"/>
<listener class-name="com.games24x7.e2e.core.listener.Retrylistener"/>
</listeners>
<test thread-count="1" parallel="methods" name="regression" verbose="2">
<classes>
<class name="com.appium.webtest">
<methods>
<include name="test1"/>
<include name="test2"/>
</methods>
</class>
</classes>
</test>

</suite>`

**Comment by saikrishna321** [comment]
@SushanthN22 can you show different class with same method names how it would like ?

**Comment by SushanthN22** [comment]
> @SushanthN22 can you show different class with same method names how it would like ?

@saikrishna321 Please find below, basically the method/test name which we pass as argument, will be looked up on all classes and will construct a xml file.

Screenshot 2023-11-23 at 3 51 41 PM

**Comment by saikrishna321** [comment]
@SushanthN22 can you show the Runner class for this pls

**Comment by AnilPatidar** [comment]
ATDRunner parallelThread = new ATDRunner();
            
            **Normal case (run the test based on groups ):**   
                  runStatus = parallelThread.runner(testPackageName);

            **Running specific cases or failed cases:**
                runStatus = parallelThread.runner(testPackageName, testCases);
            
            **Details :** 
            
             **if ( runFailedCases)  {** //reading  testng-failed.xml and make a list of test cases
           
                   List testCases= readTestNameFromTestNGFailedXml(); //reading  testng-failed.xml and make a list of test cases
                    runStatus = parallelThread.runner(testPackageName, testCases);
                }
            }
            
            here testCaseName is a system prop which we are taking from users to provide, 
            example : test1,test2,test3
            
           **else  if(testCaseName != null && !testCaseName.trim().isEmpty() ){**
                testCases.addAll(Arrays.asList(testCaseName.replaceAll("\\s", "").split(",")));
                runStatus = parallelThread.runner(testPackageName, testCases);
            }

**Comment by saikrishna321** [comment]
@AnilPatidar Can you please update the docs https://github.com/AppiumTestDistribution/AppiumTestDistribution/blob/main/docs/testng.md

Will merge this after the docs are done.

**Comment by SushanthN22** [comment]
Thanks @AnilPatidar for attaching the code on my absence. We will connect and update the doc

**Comment by saikrishna321** [comment]
@AnilPatidar @SushanthN22 Any updates on this PR??

**Comment by SushanthN22** [comment]
> @AnilPatidar @SushanthN22 Any updates on this PR??

@saikrishna321 @AnilPatidar Can you please check now and let me know if any changes required

**Comment by saikrishna321** [comment]
>             ATDRunner parallelThread = new ATDRunner();
> 
>             
> 
>             **Normal case (run the test based on groups ):**   
> 
>                   runStatus = parallelThread.runner(testPackageName);
> 
> 
> 
>             **Running specific cases or failed cases:**
> 
>                 runStatus = parallelThread.runner(testPackageName, testCases);
> 
>             
> 
>             **Details :** 
> 
>             
> 
>             CASE 1: 
> 
>             
> 
>              **if ( runFailedCases)  {** //reading  testng-failed.xml and make a list of test cases
> 
>            
> 
>                    List testCases= readTestNameFromTestNGFailedXml(); //reading  testng-failed.xml and make a list of test cases
> 
>                     runStatus = parallelThread.runner(testPackageName, testCases);
> 
>                 }
> 
>             }
> 
>             
> 
>             CASE 2: 
> 
>             
> 
>             here testCaseName is a system prop which we are taking from users to provide, 
> 
>             example : test1,test2,test3
> 
>             
> 
>            **else  if(testCaseName != null && !testCaseName.trim().isEmpty() ){**
> 
>                 testCases.addAll(Arrays.asList(testCaseName.replaceAll("\\s", "").split(",")));
> 
>                 runStatus = parallelThread.runner(testPackageName, testCases);
> 
>             } 
> 
>             
> 
>            
> 
> 

@SushanthN22 you need to add this to the doc.

**Comment by SushanthN22** [comment]
@saikrishna321 Updated please check

**Comment by SushanthN22** [comment]
@saikrishna321 Any Update here

**Pull request merged**
