### PR TITLE
Fix : toAbsolutePath was not required.

### PR DESCRIPTION
**Pull request by AnilPatidar**
There was a line of code which was not required. it getBasePath() method should only return the value mentioneed in basePath property, but not the absolute path for it.

I have tested it . it is not required.

path.normalize().toAbsolutePath().toString()

private String getBasePath() {
        Path path = FileSystems.getDefault().getPath(Capabilities.getInstance()
                .getCapabilities().get("basePath").toString());
        String basePath = path.normalize().toAbsolutePath().toString();
        LOGGER.info("Picking UserSpecified Base Path");
        return basePath;
    }

### CODE REVIEW

**Comment by AnilPatidar** [comment]
@saikrishna321 it's a quick fix for a small issue caused in my previous PR.

**Review by saikrishna321 — APPROVED** [review]

**Comment by SrinivasanTarget** [comment]
Do we really need basepath? Did you checked testing every platform & cloud without giving base path? If we really need it then why don't we give it while starting the server itself instead of all these hacks?

**Comment by AnilPatidar** [comment]
@SrinivasanTarget thanks for highlighting , https://github.com/AppiumTestDistribution/AppiumTestDistribution/pull/1101/#issuecomment-1764580341

Previously it was always set while starting the server. that's where pcloudy stopped working. since it does not require base path, so we kept it optional. if this prop is not set, we will default set it.
if someone set it, we will ready this prop and set it.

**Comment by AnilPatidar** [comment]
@saikrishna321  conflicts are resolved.

**Pull request merged**
