### PR TITLE
Fixed #533, NullPointerException when @BeforeXXX and @AfterXXX methods are used in tests.

### LINKED ISSUE #533: Getting null pointer in Before methods
This is my test class. Am I missing anything? 

public class LoginTests{

	LoginPage login;

	@BeforeClass
	public void dataSetup() throws IOException, InterruptedException {
		login = new LoginPage(AppiumDriverManager.getDriver());
		login.login("Login URL");
	}
	
	@Test(groups = "Parallel")
	public void loginWithValidUser() throws InterruptedException, IOException {
		login = new LoginPage(AppiumDriverManager.getDriver());
		Assert.assertTrue(login.isUserLoggedIn());
	}

	@Test(groups = "Parallel")
	public void logOut() throws InterruptedException, IOException {
		login = new LoginPage(AppiumDriverManager.getDriver());
		Assert.assertTrue(login.isUserLoggedIn());
	}

}

Error log:
java.lang.NullPointerException
	at com.appium.manager.TestLogger.endLogging(TestLogger.java:68)
	at com.appium.manager.AppiumParallelTestListener.afterInvocation(AppiumParallelTestListener.java:84)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:566)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:545)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by WasiqB**
Outdated dependencies are also updated.

### CODE REVIEW

**Comment by saikrishna321** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/main/java/com/appium/manager/ATDRunner.java  -3
+ src/main/java/com/appium/utils/ConfigFileManager.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/saikrishna321/AppiumTestDistribution/pullRequest?prid=4635921&bid=15534007)

**Comment by saikrishna321** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/main/java/com/appium/manager/ATDRunner.java  -3
+ src/main/java/com/appium/utils/ConfigFileManager.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/saikrishna321/AppiumTestDistribution/pullRequest?prid=4635921&bid=15534007)

**Comment by WasiqB** [comment]
@saikrishna321 , can this PR be considered as an optimisation of existing class?

**Comment by saikrishna321** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/main/java/com/appium/utils/ConfigFileManager.java  -6
+ src/main/java/com/appium/manager/ATDRunner.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/saikrishna321/AppiumTestDistribution/pullRequest?prid=4635921&bid=15534007)

**Comment by saikrishna321** [comment]
@WasiqB Can you please look at why CI is failing?

**Comment by WasiqB** [comment]
@saikrishna321 , I am working on #533 which I replicated in the last commit. I'll work on resolving it in sometime.

**Comment by saikrishna321** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/main/java/com/appium/utils/ConfigFileManager.java  -6
+ src/main/java/com/appium/manager/ATDRunner.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/saikrishna321/AppiumTestDistribution/pullRequest?prid=4635921&bid=15534007)

**Comment by saikrishna321** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/main/java/com/appium/utils/ConfigFileManager.java  -6
+ src/main/java/com/appium/manager/ATDRunner.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/saikrishna321/AppiumTestDistribution/pullRequest?prid=4635921&bid=15534007)

**Pull request merged**
