### PR TITLE
Added ability to run Multidevice-multi-app tests

### PR DESCRIPTION
**Pull request by anandbagmar**
Added ability for ATD to create a driver for another app.
Existing tests are passing on local

### CODE REVIEW

**Comment by anandbagmar** [comment]
@saikrishna321 , @SrinivasanTarget - can you please take a look at this PR

**Comment by saikrishna321** [comment]
What is the usage of this PR ?

**Comment by anandbagmar** [comment]
@saikrishna321 
This is the example I am trying to automate:
The test needs 2 different types of apps to complete the end-2-end flow. In fact, in some cases, there can be more than 2 such apps involved in the workflow, on different platforms.

```
@multidevice
Feature: Test order placement and delivery

  @multiuser-android
  Scenario: Verify error message on invalid login
    Given "I" start "Amazon-Android" app
    And I have placed an order for a "book"
    When "deliveryAgent" starts "Amazon-Delivery-Android" app
    And "deliveryAgent" delivers the order
    Then "I" can see the order status as "delivered"
```

ATD currently creates a driver using the same capabilities. This PR makes it possible for passing different capabilities to each driver instantiation.

I am passing these capabilities from teswiz (https://github.com/znsio/teswiz) 

Hope this clarifies

**Comment by saikrishna321** [comment]
Yes, can you show an example how users can use this implementation 

Thanks

**Comment by anandbagmar** [comment]
@saikrishna321 - teswiz, which uses ATD internally, has the capability to initialize new drivers if the test scenario requires multiple "persona" interactions.

Example:

```
@multiuser-android
Scenario: Host (on Android) removes a Guest (on Android) from the meeting
  Given "Host" signs up (using API), logs-in and starts an instant meeting on "android"
  When "Guest" joins the meeting from "android"
  Then "Host" should not be able to invite invalid contact in search bar on Participant Screen
  When "Host" removes "Guest" from meeting
  Then "Guest" should land on Splash screen
```


The above test shows there are 2 people - "Host" and "Guest", each using the same app, and there is an orchestration between these personas.

Now there is a new requirement. In complex scenarios, there are multiple apps involved in the end-2-end flow.
Example:

```
@multidevice
Feature: Test order placement and delivery

  @multiuser-android
  Scenario: Verify error message on invalid login
    Given "I" start "Amazon-Android" app
    And I have placed an order for a "book"
    When "deliveryAgent" starts "Amazon-Delivery-Android" app
    And "deliveryAgent" delivers the order
    Then "I" can see the order status as "delivered"
```

This means, "I" am on the Amazon app (on android), and the "deliveryAgent" is on the Amazon Delivery app. 
We needed a capability to install different apps for each user persona and have interaction / orchestration between them to ensure end-2-end scenario can be validated.

This PR supports the ability to create a Appium driver for different apps on demand as per requirement of the test scenario.

I have run the ATD tests locally and in the PR flow as well. Tests passed on Local and in SauceLabs, but there is some unrelated problem in BrowserStack.

Hope this clarifies.

cc @SrinivasanTarget

**Comment by saikrishna321** [comment]
Thanks for the clarification. How will a user with TestNg use this feature ?

**Comment by anandbagmar** [comment]
I have implemented this method in teswiz Drivers.java to request additional drivers from ATD:
https://github.com/znsio/teswiz/blob/main/src/main/java/com/znsio/e2e/tools/Drivers.java


```
    private AppiumDriver allocateNewDeviceAndStartAppiumDriver(String testName, String capabilityFile) {
        try {
            DeviceAllocationManager deviceAllocationManager = DeviceAllocationManager.getInstance();
            AppiumDevice availableDevice = deviceAllocationManager.getNextAvailableDevice();
            deviceAllocationManager.allocateDevice(availableDevice);
            AppiumDriver driver = new AppiumDriverManager().startAppiumDriverInstance(testName, capabilityFile);
            updateAvailableDeviceInformation(availableDevice);
            ReportPortal.emitLog("allocateNewDeviceAndStartAppiumDriver: Device Info\n" + availableDevice, DEBUG, new Date());
            return driver;
        } catch (Exception e) {
            LOGGER.info(ExceptionUtils.getStackTrace(e));
            throw new RuntimeException(e);
        }
    }
```

The above method can be called from any testng / junit / cucumber-based framework.

**Pull request merged**
