### PR TITLE
Unable to create chrome session for headspin execution

### PR DESCRIPTION
**Pull request by AnilPatidar**
There was an issue in ATD, due to which headspin chrome session was not getting created, the browserName was explicitly added as null

### CODE REVIEW

**Comment by AnilPatidar** [comment]
@saikrishna321  this PR needs to be merge with ATD , let me know the process , since i am doing it first time

**Comment by saikrishna321** [comment]
Thanks for the PR. Can you please fix the linting issue

**Comment by AnilPatidar** [comment]
@saikrishna321  i have fixed lint issues ,please merge the PR

**Comment by AnilPatidar** [comment]
Thanks alot @saikrishna321  for quick merge .

**Pull request merged**
