### PR TITLE
added ability to override capabilites from environment variables

### PR DESCRIPTION
**Pull request by anandbagmar**
added ability to override capabilites from environment variables

### CODE REVIEW

**Comment by saikrishna321** [comment]
@anandbagmar How would you pass the app capability for both iOS real device and iOS Simulator?

**Comment by anandbagmar** [comment]
@saikrishna321 - if we want Platform specific updates, I can update the PR based on that. 
Ex: to override any capability, set the env var as:
`android.app=....` - which will update / add to the android config only. ]

Would that approach be better?

**Comment by saikrishna321** [comment]
@anandbagmar We need to change approach after this PR got merged https://github.com/AppiumTestDistribution/AppiumTestDistribution/pull/478 

Now we will default to "app": {
   "local": ".../../something.apk",
   "cloud": "CloudURL to apk"
}

**Comment by anandbagmar** [comment]
Cool. Will take a look and update the PR

**Comment by sumitbera** [comment]
@anandbagmar  This will be very helpful. I'm also stuck at this point. I have to use APK path from Bitrise CI. Would be really nice if you finish this

**Comment by anandbagmar** [comment]
@saikrishna321 , @SrinivasanTarget - I have updated this PR. Here are some examples how to update the capabilities using environment variables:

- to update android's app path, set env var as: 
`atd.android.app=<new path>`
- To update a specific property as part of an array, 
`atd.hostMachines.0.appiumServerPath=<new path>`
- To update the 1st simulator's device name in the 1st hostMachine: `atd.hostMachines.0.simulators.0.deviceName=<new name>`

Let me know if this seems ok

**Comment by anandbagmar** [comment]
@saikrishna321 , @SrinivasanTarget  - thanks for merging the PR. Any idea when will this be available via maven, and with what version #?

**Comment by saikrishna321** [comment]
The next version will be major release v12.0.0 - cloud support and contract change on _app_ capability. 

Once the docs are done we can release

**Comment by anandbagmar** [comment]
ok. Hopefully that happens soon :) Thanks!

**Pull request merged**
